### ISSUE TITLE
How to setup the CLI?

### ISSUE THREAD

**Issue by FezVrasta** [RollingVersions/RollingVersions#54]
Hi, I can't find any instruction to setup the CLI, may you point me in the right direction please?

**Comment by FezVrasta** [comment]
So, I looked at the is-promise repo and it seems like one needs to use the `rollingversions` npm package, here's a GitHub Actions example:

```
name: Publish
on: [push]

jobs:
  publish-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run: npx rollingversions publish --dry-run
  
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run: npx rollingversions publish
```


What I don't understand is how to make the `publish` step run only when I decide it to.

I was expecting the GitHub integration to automatically create a release PR that, once merged, could be used to trigger the publish action, but it doesn't seem to be the case?
